# -*- coding: utf-8 -*-
"""载荷信息流仿真软件 —— 数据层定义。

内容：
  UNITS   : 各单机（chain 节点）的默认增益/噪声系数/功耗/质量与规格
  PARAMS  : 全部可调工程参数（symbol 与知识图谱 attributes.symbol 一致）
  PRESETS : 4 个典型场景预设
  MODCOD  : DVBS2X 阶梯（η 与 C/N 门限，含 1.0dB 实现损耗）
  BANDS   : 频段典型参数（雨衰参考值/可用带宽/复用色数）
"""
from __future__ import annotations

# ----------------------------------------------------------------
# 单机库：chain 中每个节点的电气与物理默认值
#   kind: amp(有源放大) / pass(无源损耗) / dig(数字处理) / opt(光学) / mech(机构) / ctrl(控制)
#   g_db: 增益(dB)，负值为插损；dig/opt/mech/ctrl 类通常为 0（不改变射频电平）
#   nf_db: 噪声系数(dB)，仅 amp 有意义
#   T_phys: 无源器件物理温度(K)，用于 T=(L-1)*T_phys
# ----------------------------------------------------------------
UNITS = {
    # ---- 天线发射通道 ----
    "power_combiner": dict(cn="功率合成器", kind="pass", g_db=-0.8, p_w=0, m_kg=1.2,
                           specs={"η_cmb": 85}, note="8 路合成，效率 85% → 插损 0.8dB"),
    "phase_shifter": dict(cn="移相器", kind="pass", g_db=-1.0, p_w=0.6, m_kg=0.05,
                          specs={"n_bit": 6}, note="6 位数字移相，量化误差 ≈180/2^6=2.8°"),
    "var_atten": dict(cn="可变衰减器", kind="pass", g_db=-0.5, p_w=0.2, m_kg=0.03,
                      specs={"Δ_eq": 0.5}, note="幅频/群时延均衡"),
    "tx_filter": dict(cn="发射滤波器", kind="pass", g_db=-1.2, p_w=0, m_kg=0.8,
                      specs={"A_rej": 60}, note="带外抑制 60dB，满足带外发射限值"),
    "circulator": dict(cn="环行器/隔离器", kind="pass", g_db=-0.4, p_w=0, m_kg=0.6,
                       specs={"I_iso": 100}, note="收发隔离 ≥100dB（c-15）"),
    "feed": dict(cn="馈源与馈电网络", kind="pass", g_db=-0.8, p_w=0, m_kg=2.5,
                 specs={"η_ill": 68}, note="照射效率 68%，影响天线总效率 η"),
    # ---- 天线接收通道 ----
    "rx_filter": dict(cn="接收滤波器", kind="pass", g_db=-0.9, p_w=0, m_kg=0.7,
                      specs={"A_img": 60}, note="镜像/带外抑制 60dB"),
    "rx_switch": dict(cn="接收通道开关", kind="pass", g_db=-0.6, p_w=0.3, m_kg=0.2,
                      specs={"I_sw": 80}, note="开关隔离度 80dB"),
    "tr_module": dict(cn="T/R 组件", kind="amp", g_db=20.0, nf_db=2.0, p_w=8.0, m_kg=0.03,
                      specs={"T_j": 105, "P_tr": 8.0, "P_tr_out": 5.0},
                      note="接收通道增益 20dB / NF 2.0dB；结温须 ≤125℃（c-16）"),
    # ---- 波束链路 ----
    "beam_former": dict(cn="波束赋形网络", kind="pass", g_db=-1.5, p_w=12.0, m_kg=4.0,
                        specs={"N_bf": 64}, note="成形通道数须 ≥ 波束数（c-25）"),
    "beam_port": dict(cn="波束端口", kind="pass", g_db=-0.6, p_w=0, m_kg=1.0,
                      specs={"N_port": 64}, note="端口数须 ≥ 波束数（c-25）"),
    "beam_switch": dict(cn="波束切换开关矩阵", kind="pass", g_db=-1.2, p_w=3.0, m_kg=1.5,
                        specs={"I_sw": 80}, note="波束跳变体制核心"),
    "cal_network": dict(cn="波束校准网络", kind="pass", g_db=-0.5, p_w=2.0, m_kg=0.8,
                        specs={"Δ_cal": 0.3}, note="校准精度须优于幅相一致性（c-23）"),
    "ant_ctrl": dict(cn="天线控制单元 ACU", kind="ctrl", g_db=0.0, p_w=15.0, m_kg=3.0,
                     specs={"t_acu": 50}, note="波束切换响应 50ms"),
    # ---- 转发器接收侧 ----
    "lna": dict(cn="低噪声放大器 LNA", kind="amp", g_db=35.0, nf_db=1.6, p_w=6.0, m_kg=0.4,
                specs={"G_lna": 35.0, "NF_lna": 1.6}, note="Ka 典型 NF 1.6dB（Ku 1.2 / L 0.8），A/B 冷备"),
    "imux": dict(cn="输入多工器 IMUX", kind="pass", g_db=-1.5, p_w=0, m_kg=2.0,
                 specs={"N_imux": 8}, note="8 通道，通道间隔须匹配频率规划"),
    "dconv": dict(cn="下变频器 DCONV", kind="amp", g_db=-2.0, nf_db=8.0, p_w=4.0, m_kg=0.5,
                  specs={"G_conv": -2.0}, note="变频损耗 2dB，镜像抑制 >60dBc"),
    "equalizer": dict(cn="均衡器/衰减器", kind="pass", g_db=-1.0, p_w=0, m_kg=0.3,
                      specs={"Δ_eq": 1.0}, note="通带平坦度均衡"),
    "filter_rf": dict(cn="射频滤波器", kind="pass", g_db=-1.0, p_w=0, m_kg=0.5,
                      specs={"A_rf": 60}, note="带外抑制 60dB"),
    "lo_source": dict(cn="频率源/本振", kind="ctrl", g_db=0.0, p_w=8.0, m_kg=1.0,
                      specs={"L_φ": -95}, note="相位噪声 −95dBc/Hz@10kHz，影响 EVM"),
    # ---- 转发器功放侧 ----
    "twta": dict(cn="行波管功放 TWTA", kind="amp", g_db=50.0, p_w=310.0, m_kg=6.0,
                 specs={"P_twta": 180.0, "η_twta": 58}, note="Ka 180W / 效率 58%，P_dc=P_out/η"),
    "sspa": dict(cn="固态功放 SSPA", kind="amp", g_db=45.0, p_w=222.0, m_kg=3.0,
                 specs={"P_sspa": 100.0, "η_sspa": 45, "IMD3": -25},
                 note="100W / 效率 45%，线性度优于 TWTA"),
    "mpa": dict(cn="多功放矩阵 MPA", kind="amp", g_db=48.0, p_w=400.0, m_kg=8.0,
                specs={"N_mpa": 8, "η_sspa": 42}, note="8×8 功率池，单管故障可重构"),
    "epc": dict(cn="电子功率调节器 EPC", kind="ctrl", g_db=0.0, p_w=5.0, m_kg=2.0,
                specs={"V_hv": 6.0}, note="高压 6kV，含过流过压保护"),
    "OMUX_": None,
    "omux": dict(cn="输出多工器 OMUX", kind="pass", g_db=-1.8, p_w=0, m_kg=3.5,
                 specs={"N_omux": 8}, note="8 通道，插损 1.8dB"),
    "uconv": dict(cn="上变频器 UCONV", kind="amp", g_db=-2.0, nf_db=8.0, p_w=4.0, m_kg=0.5,
                  specs={"G_conv": -2.0}, note="变频损耗 2dB"),
    "switch_matrix": dict(cn="微波开关矩阵", kind="pass", g_db=-1.5, p_w=4.0, m_kg=1.5,
                          specs={"I_sw": 80}, note="隔离度 80dB，切换 ns 级"),
    # ---- DTP 数字化 ----
    "adc": dict(cn="数字信道化 ADC", kind="dig", g_db=0.0, p_w=25.0, m_kg=1.2,
                specs={"B_adc": 1200}, note="采样带宽 1200MHz，ENOB ≥10bit，SFDR ≥70dBc"),
    "dswitch": dict(cn="星上交换矩阵", kind="dig", g_db=0.0, p_w=45.0, m_kg=3.0,
                    specs={"C_dsw": 100}, note="非阻塞交换容量 100Gbps（c-14）"),
    "dac": dict(cn="数模转换 DAC", kind="dig", g_db=0.0, p_w=20.0, m_kg=1.0,
                specs={"SFDR": 70}, note="SFDR ≥70dBc"),
    # ---- 再生基带 ----
    "demod": dict(cn="解调器", kind="dig", g_db=0.0, p_w=18.0, m_kg=1.0,
                  specs={"CN_thr": 3.1}, note="QPSK~32APSK 解调，ACM/VCM 自适应"),
    "decoder": dict(cn="译码器", kind="dig", g_db=0.0, p_w=22.0, m_kg=1.2,
                    specs={"G_code": 6.5}, note="LDPC/BCH，编码增益 6.5dB"),
    "encoder": dict(cn="编码器", kind="dig", g_db=0.0, p_w=15.0, m_kg=0.8,
                    specs={"G_code": 6.5}, note="与译码器配对"),
    "modulator": dict(cn="调制器", kind="dig", g_db=0.0, p_w=15.0, m_kg=0.8,
                      specs={"MODCOD": "32APSK 5/6"}, note="DVBS2X MODCOD 阶梯"),
    "router_unit": dict(cn="星上路由交换单元", kind="dig", g_db=0.0, p_w=30.0, m_kg=2.5,
                        specs={"N_route": 4096, "N_rt": 4096}, note="路由表 4096 条，单跳选路 <1ms"),
    # ---- 展开与指向 ----
    "deploy": dict(cn="天线展开机构", kind="mech", g_db=0.0, p_w=0, m_kg=18.0,
                   specs={"δ_dep": 0.20}, note="到位精度 0.20mm RMS，须 ≤ δ_surf（c-5）"),
    "pointing": dict(cn="天线指向机构", kind="mech", g_db=0.0, p_w=25.0, m_kg=15.0,
                     specs={"Δ_pnt": 0.02}, note="步距 0.02°，重复精度决定 θ_e"),
    # ---- 激光 ----
    "beacon_laser": dict(cn="信标激光器", kind="opt", g_db=0.0, p_w=8.0, m_kg=0.6,
                         specs={"P_bcn": 3.0}, note="3W 信标，发散角 3mrad 用于粗捕获"),
    "acq_sensor": dict(cn="捕获跟踪传感器", kind="opt", g_db=0.0, p_w=6.0, m_kg=0.8,
                       specs={"S_acq": -55}, note="灵敏度 −55dBm，视场 ±10°"),
    "atp_coarse": dict(cn="ATP 粗跟踪机构", kind="mech", g_db=0.0, p_w=20.0, m_kg=6.0,
                       specs={"P_acq": 97, "t_acq": 30}, note="万向架两轴，捕获概率 ≥95%（c-18）"),
    "fsm": dict(cn="精跟踪快速反射镜 FSM", kind="mech", g_db=0.0, p_w=10.0, m_kg=1.2,
                specs={"σ_track": 0.8, "θ_fsm": 3.0}, note="精度 0.8μrad ≤1μrad，偏转 ±3mrad，带宽 800Hz"),
    "tx_laser": dict(cn="通信激光器", kind="opt", g_db=0.0, p_w=12.0, m_kg=0.8,
                     specs={"P_opt": 1.0}, note="1W @1550nm，线宽 <100kHz"),
    "edfa": dict(cn="光放大器 EDFA", kind="opt", g_db=25.0, p_w=25.0, m_kg=2.0,
                 specs={"G_edfa": 25}, note="增益 25dB，噪声指数 5dB"),
    "optical_antenna": dict(cn="光学天线", kind="opt", g_db=0.0, p_w=0, m_kg=4.5,
                            specs={"D_opt": 135}, note="Φ135mm 卡塞格林，η≈0.6"),
    "photodetector": dict(cn="光探测器", kind="opt", g_db=0.0, p_w=5.0, m_kg=0.4,
                          specs={"S_opt": -42}, note="APD/平衡探测，DPSK 灵敏度优于 OOK 约 6dB"),
    "dpsk_modem": dict(cn="DPSK 调制解调模块", kind="dig", g_db=0.0, p_w=20.0, m_kg=1.5,
                       specs={"CN_dpsk": 8.0}, note="DPSK 门限 ≈8dB（c-19）"),
    "opt_switch": dict(cn="光开关", kind="opt", g_db=-1.5, p_w=3.0, m_kg=0.5,
                       specs={}, note="多链路切换与主备倒换，插损 1.5dB"),
    "laser_ctrl": dict(cn="激光通信控制器", kind="ctrl", g_db=0.0, p_w=12.0, m_kg=2.0,
                       specs={}, note="ATP 状态机与建链/断链管理"),
    # ---- 智能处理 ----
    "baseband": dict(cn="基带处理单元", kind="dig", g_db=0.0, p_w=35.0, m_kg=3.0,
                     specs={"R_bb": 2000}, note="基带吞吐 2000Mbps，同步精度 <1μs"),
    "ai_unit": dict(cn="AI 推理单元", kind="dig", g_db=0.0, p_w=30.0, m_kg=2.0,
                    specs={"AI_TOPS": 20}, note="20TOPS，支持目标/云检测与业务预测"),
    "dpu": dict(cn="数据处理单元 DPU", kind="dig", g_db=0.0, p_w=28.0, m_kg=2.5,
                specs={"R_dpu": 1500, "CR": 4}, note="CCSDS 压缩比 4:1，等效降低总线与存储需求"),
    "storage": dict(cn="大容量存储器", kind="dig", g_db=0.0, p_w=20.0, m_kg=5.0,
                    specs={"E_store": 4.0}, note="4Tbit，含 EDAC 三模冗余"),
    "data_bus": dict(cn="星上数据总线", kind="dig", g_db=0.0, p_w=10.0, m_kg=1.5,
                     specs={"R_bus": 4000}, note="FC-AE 4000Mbps，须 ≥ 载荷数据率（c-20）"),
    "obc_payload": dict(cn="星载计算机", kind="ctrl", g_db=0.0, p_w=18.0, m_kg=3.5,
                        specs={"MIPS": 4000}, note="4000MIPS，FDIR 覆盖关键单机"),
    "reconfig_ctrl": dict(cn="在轨重构控制器", kind="ctrl", g_db=0.0, p_w=8.0, m_kg=1.0,
                          specs={"t_rec": 5}, note="重构指令生效 5s"),
}
UNITS.pop("OMUX_", None)

# ----------------------------------------------------------------
# 频段典型参数
# ----------------------------------------------------------------
BANDS = {
    "L":      dict(f_up=1.6,   f_down=1.5,   A_up=0.2,  A_dn=0.2,  B_total=30,   k_reuse=4, lam_note="λ≈0.19m"),
    "S":      dict(f_up=2.1,   f_down=2.3,   A_up=0.3,  A_dn=0.3,  B_total=100,  k_reuse=4, lam_note="λ≈0.14m"),
    "C":      dict(f_up=6.0,   f_down=4.0,   A_up=0.8,  A_dn=0.5,  B_total=500,  k_reuse=4, lam_note="λ≈0.075m"),
    "X":      dict(f_up=8.0,   f_down=7.5,   A_up=1.2,  A_dn=1.0,  B_total=800,  k_reuse=4, lam_note="λ≈0.040m"),
    "Ku":     dict(f_up=14.0,  f_down=12.0,  A_up=2.5,  A_dn=2.0,  B_total=500,  k_reuse=4, lam_note="λ≈0.025m"),
    "Ka":     dict(f_up=30.0,  f_down=20.0,  A_up=12.0, A_dn=7.0,  B_total=2500, k_reuse=4, lam_note="λ≈0.015m"),
    "Q/V":    dict(f_up=50.0,  f_down=40.0,  A_up=20.0, A_dn=14.0, B_total=3000, k_reuse=7, lam_note="λ≈0.0075m"),
    "激光":    dict(f_up=193.4e3, f_down=193.4e3, A_up=0, A_dn=0,   B_total=10000, k_reuse=1, lam_note="λ=1550nm"),
}

# ----------------------------------------------------------------
# DVBS2X MODCOD 阶梯（Normal FECFRAME）
#   cn_req = Es/N0 + 1.0dB 实现损耗（与 a-link-impl 一致）
# ----------------------------------------------------------------
MODCOD = [
    dict(name="QPSK 1/4",   eta=0.49, esn0=-2.4),
    dict(name="QPSK 1/3",   eta=0.66, esn0=-1.2),
    dict(name="QPSK 2/5",   eta=0.79, esn0=-0.3),
    dict(name="QPSK 1/2",   eta=0.99, esn0=1.0),
    dict(name="QPSK 3/5",   eta=1.19, esn0=2.3),
    dict(name="QPSK 2/3",   eta=1.32, esn0=3.1),
    dict(name="QPSK 3/4",   eta=1.49, esn0=4.1),
    dict(name="QPSK 4/5",   eta=1.59, esn0=4.7),
    dict(name="QPSK 5/6",   eta=1.65, esn0=5.2),
    dict(name="QPSK 8/9",   eta=1.76, esn0=6.2),
    dict(name="QPSK 9/10",  eta=1.79, esn0=6.4),
    dict(name="8PSK 3/5",   eta=1.78, esn0=5.5),
    dict(name="8PSK 2/3",   eta=1.98, esn0=6.6),
    dict(name="8PSK 3/4",   eta=2.22, esn0=7.9),
    dict(name="8PSK 5/6",   eta=2.48, esn0=9.4),
    dict(name="8PSK 8/9",   eta=2.64, esn0=10.7),
    dict(name="8PSK 9/10",  eta=2.85, esn0=11.0),
    dict(name="16APSK 2/3", eta=2.64, esn0=8.9),
    dict(name="16APSK 3/4", eta=2.97, esn0=10.2),
    dict(name="16APSK 4/5", eta=3.16, esn0=11.0),
    dict(name="16APSK 5/6", eta=3.30, esn0=11.6),
    dict(name="16APSK 8/9", eta=3.52, esn0=12.9),
    dict(name="16APSK 9/10", eta=3.70, esn0=13.2),
    dict(name="32APSK 3/4", eta=3.70, esn0=12.7),
    dict(name="32APSK 4/5", eta=3.95, esn0=13.6),
    dict(name="32APSK 5/6", eta=4.12, esn0=14.3),
    dict(name="32APSK 8/9", eta=4.40, esn0=15.6),
    dict(name="32APSK 9/10", eta=4.45, esn0=15.9),
]
for m in MODCOD:
    m["cn_req"] = round(m["esn0"] + 1.0, 2)   # 含 1.0dB 实现损耗

# ----------------------------------------------------------------
# 可调参数（symbol 与知识图谱 attributes.symbol 对齐）
#   (sym, label, unit, default, group, kind, note, options)
# ----------------------------------------------------------------
P = lambda *a: dict(zip(("sym", "label", "unit", "def", "group", "kind", "note", "options"),
                        list(a) + [None] * (8 - len(a))))

PARAMS = [
    # --- 任务与轨道 ---
    P("orbit", "轨道类型", "", "GEO", "任务轨道", "select", "GEO 斜距≈38000km；LEO≈600~2000km",
      ["GEO", "MEO", "LEO", "SSO", "HEO"]),
    P("d_slant", "上行斜距 d", "km", 38000, "任务轨道", "num", "c-7 FSPL 输入；GEO 30°仰角约 38000km"),
    P("d_dl", "下行斜距 d", "km", 38000, "任务轨道", "num", "下行 FSPL 输入，通常与上行相同"),
    P("el_deg", "地面站仰角", "°", 30, "任务轨道", "num", "雨衰按 sin(30°)/sin(el) 归一"),
    P("A_avail", "链路可用性", "%", 99.9, "任务轨道", "select", "超越概率 p=100−A；A(p)∝p^−0.6",
      ["99.0", "99.5", "99.9", "99.95", "99.99"]),
    P("L_life", "设计寿命", "年", 15, "任务轨道", "num", "GEO 通常 ≥15 年"),
    # --- 频段与频率规划 ---
    P("band", "工作频段", "", "Ka", "频段规划", "select", "切换后自动载入该频段典型雨衰/带宽/色数",
      list(BANDS.keys())),
    P("f_up", "上行频率 f", "GHz", 30.0, "频段规划", "num", "c-7 L_fs=20lg(d)+20lg(f)−147.55"),
    P("f_down", "下行频率 f", "GHz", 20.0, "频段规划", "num", "c-4/c-5 波长 λ=0.3/f(GHz) m"),
    P("A_up_ref", "上行雨衰参考值", "dB", 12.0, "频段规划", "num", "0.01% 超越概率、30°仰角典型值"),
    P("A_dn_ref", "下行雨衰参考值", "dB", 7.0, "频段规划", "num", "0.01% 超越概率、30°仰角典型值"),
    P("A_atm", "大气损耗（上行）", "dB", 0.4, "频段规划", "num", "氧气/水汽吸收，Ka 约 0.4dB"),
    P("A_atm_dl", "大气损耗（下行）", "dB", 0.2, "频段规划", "num", "20GHz 约 0.2dB"),
    P("L_pol", "极化失配损耗", "dB", 0.3, "频段规划", "num", "典型 0.3dB"),
    P("L_impl", "实现损耗", "dB", 1.0, "频段规划", "num", "设备实现损耗，含调制解调门限余量"),
    P("B_total", "频段可用总带宽", "MHz", 2500, "频段规划", "num", "c-13 N_beam×B_beam ≤ B_total×k_reuse"),
    P("k_reuse", "频率复用色数", "", 4, "频段规划", "select", "c-13 频率规划；4 色/7 色复用", ["1", "2", "3", "4", "7"]),
    # --- 天线体制与电气 ---
    P("ant_type", "天线体制", "", "反射面天线", "天线", "select",
      "c-22 须满足需求模式；相控阵用 c-3，反射面用 c-4",
      ["相控阵天线", "反射阵天线", "反射面天线", "伞状可展开天线", "喇叭天线", "螺旋天线"]),
    P("D_ap", "口径/阵面尺寸 D", "m", 2.5, "天线", "num", "c-4 G_refl=10lg(η(πD/λ)²)；θ_3dB≈70λ/D"),
    P("N_el", "阵元数 N_el", "", 1024, "天线", "num", "c-3 G_pa=10lg(N_el×η)+G_el（相控阵用）"),
    P("G_el", "单元增益 G_el", "dBi", 6.0, "天线", "num", "c-3 相控阵单元增益"),
    P("η_ill", "口面/照射效率 η", "%", 68, "天线", "num", "反射面口面效率或阵面效率"),
    P("θ_scan", "扫描角 θ_scan", "°", 0, "天线", "num", "相控阵扫描损耗 cos^1.5θ，正射填 0"),
    P("G_ant_ovr", "天线增益手动覆盖", "dBi", "", "天线", "num", "留空则由 c-3/c-4 自动计算"),
    P("δ_surf", "面精度 δ_surf", "mm", 0.20, "天线", "num", "c-5 须 ≤ λ/32（Ka≈0.27mm）"),
    P("δ_dep", "展开到位精度 δ_dep", "mm", 0.20, "天线", "num", "c-5 须 ≤ δ_surf"),
    P("SLL", "旁瓣电平 SLL", "dB", -22, "天线", "num", "c-23 须 ≤ −20dB（ITU-R S.1323）"),
    P("AR", "轴比 AR", "dB", 1.5, "天线", "num", "c-23 圆极化须 ≤ 3dB"),
    P("Δ_amp", "幅相一致性(幅)", "dB", 0.4, "天线", "num", "c-23 须 ≤ 0.5dB"),
    P("Δ_phs", "幅相一致性(相)", "°", 4.0, "天线", "num", "c-23 须 ≤ 5°"),
    P("Δ_cal", "校准精度 Δ_cal", "dB", 0.3, "天线", "num", "c-23 须优于幅相一致性"),
    P("θ_e", "波束指向精度 θ_e", "°", 0.05, "天线", "num", "c-6 L_pnt=12(θ_e/θ_3dB)²"),
    P("Δ_pnt", "指向步距 Δ_pnt", "°", 0.02, "天线", "num", "机械指向最小步距"),
    P("L_feed", "馈电损耗 L_feed", "dB", 0.8, "天线", "num", "c-1 EIRP 扣减项"),
    P("N_beam", "波束数 N_beam", "", 64, "天线", "num", "c-12/c-13/c-25 核心指标"),
    P("B_beam", "单波束带宽 B_beam", "MHz", 125, "天线", "num", "c-9/c-12/c-13/c-14；整波束占用带宽"),
    P("B_carrier", "单载波占用带宽", "MHz", 36, "天线", "num",
      "c-9 C/N 与 c-11 容量的噪声带宽。整波束带宽被分割为多个载波，链路余量按单载波算；"
      "带宽减半约换来 +3dB C/N，是余量不足时的快速调整手段"),
    P("Mode", "工作模式", "", "多波束", "天线", "select", "c-22 须覆盖需求模式",
      ["单波束", "多波束", "波束跳变", "在轨重构"]),
    P("Mode_req", "需求工作模式", "", "多波束", "天线", "select", "c-22 Mode ⊇ Mode_req",
      ["单波束", "多波束", "波束跳变", "在轨重构"]),
    P("N_bf", "成形通道数 N_bf", "", 64, "天线", "num", "c-25 须 ≥ N_beam"),
    P("N_port", "波束端口数 N_port", "", 64, "天线", "num", "c-25 须 ≥ N_beam"),
    P("N_sch", "波束调度能力 N_sch", "", 64, "天线", "num", "c-25 须 ≥ N_beam"),
    P("m_ant", "天线分系统质量", "kg", 120, "天线", "num", "c-17 预算分解"),
    P("P_ant", "天线分系统功耗", "W", 350, "天线", "num", "c-17；相控阵 ≈ N_el×P_tr"),
    P("T_ant", "天线噪声温度 T_ant", "K", 50, "天线", "num", "c-2 天空噪声，GEO@30GHz 约 50K"),
    # --- 发射通道（下行）---
    P("amp_type", "功放类型", "", "TWTA", "发射通道", "select", "c-1 P_out 来源；c-16 P_dc=P_out/η",
      ["TWTA", "SSPA", "MPA"]),
    P("P_out", "功放输出功率 P_out", "W", 180, "发射通道", "num", "c-1 EIRP=P_out+G_ant−L_feed−L_tx"),
    P("η_pa", "功放效率 η", "%", 58, "发射通道", "num", "c-16 P_dc=P_out/η；TWTA 58~62%、SSPA 40~50%"),
    P("L_tx", "发射通道插损 L_tx", "dB", 4.7, "发射通道", "num", "c-1；由发射通道逐级插损自动累加，可手动覆盖"),
    P("η_cmb", "功率合成效率", "%", 85, "发射通道", "num", "合成损耗 −10lg(η)"),
    P("IMD3", "三阶交调 IMD3", "dBc", -25, "发射通道", "num", "线性度，影响高阶调制 EVM"),
    P("I_iso", "环行器隔离度 I_iso", "dB", 100, "发射通道", "num", "c-15 须 ≥ 100dB"),
    P("A_rej", "发射滤波带外抑制", "dB", 60, "发射通道", "num", "c-15 带外发射限值"),
    # --- 接收通道（上行）---
    P("NF_lna", "LNA 噪声系数", "dB", 1.6, "接收通道", "num", "c-2；Ka≤1.6 / Ku≤1.2 / L≤0.8"),
    P("G_lna", "LNA 增益", "dB", 35, "接收通道", "num", "后级噪声贡献被其抑制"),
    P("NF_trp", "接收通道总噪声系数", "dB", 2.2, "接收通道", "num", "c-2 NF，由逐级 Friis 自动算，可覆盖"),
    P("T_sys_ovr", "系统噪声温度覆盖", "K", "", "接收通道", "num", "留空则由接收链 Friis 级联自动计算"),
    P("I_sw", "开关矩阵隔离度 I_sw", "dB", 80, "接收通道", "num", "c-15"),
    # --- 转发器 ---
    P("arch", "转发体制", "", "透明转发器", "转发器", "select",
      "c-24 余量不足且已最低阶 ⇒ 改再生/DTP（ΔM_reg≥3dB）",
      ["透明转发器", "再生转发器", "DTP数字透明处理器"]),
    P("B_trp", "转发器总带宽 B_trp", "MHz", 1000, "转发器", "num", "c-14 N_ch×B_sub ≥ B_trp"),
    P("G_trp", "转发器总增益", "dB", 75, "转发器", "num", "由体制单机链逐级累加，可覆盖"),
    P("Δ_flat", "通带平坦度", "dB", 1.0, "转发器", "num", "幅频平坦度与群时延"),
    P("I_trp", "转发器收发隔离度", "dB", 85, "转发器", "num", "c-15 舱内须 ≥ 80dB"),
    P("τ_trans", "透明转发时延", "ns", 200, "转发器", "num", "c-24 透明体制近似为零"),
    P("ΔM_reg", "再生余量提升 ΔM_reg", "dB", 4.5, "转发器", "num", "c-24 典型 3~6dB（噪声不累积）"),
    P("τ_reg", "再生处理时延", "ms", 30, "转发器", "num", "c-24 解调译码再调制代价"),
    P("C_sw", "DTP 交换容量 C_sw", "Gbps", 100, "转发器", "num", "c-14 须 ≥ N_beam×B_beam 折算容量"),
    P("N_ch", "DTP 信道数 N_ch", "", 32, "转发器", "num", "c-14 N_ch×B_sub ≥ B_trp"),
    P("B_sub", "DTP 子带带宽 B_sub", "MHz", 40, "转发器", "num", "c-14 越细越灵活但功耗越大"),
    P("t_reconf", "在轨重构时间", "s", 10, "转发器", "num", "波束/带宽/功率重构切换时间"),
    P("C_dsw", "交换矩阵容量 C_dsw", "Gbps", 100, "转发器", "num", "c-14"),
    P("C_ib", "波束间交换容量 C_ib", "Gbps", 80, "转发器", "num", "星上波束交换链路"),
    P("m_trp", "转发器分系统质量", "kg", 180, "转发器", "num", "c-17"),
    P("P_trp", "转发器分系统功耗", "W", 900, "转发器", "num", "c-16 P_dc ≤ P_trp；c-17"),
    P("T_j", "T/R 组件结温 T_j", "℃", 105, "转发器", "num", "c-16 须 ≤ 125℃"),
    P("P_tr", "单组件功耗 P_tr", "W", 8.0, "转发器", "num", "c-16 阵面总功耗 ≈ N_el×P_tr"),
    # --- 地面站 ---
    P("EIRP_gs", "关口站 EIRP", "dBW", 75, "地面站", "num", "上行 C/N0 输入；GEO 关口站典型 75dBW"),
    P("GT_gs", "地面站 G/T", "dB/K", 15, "地面站", "num", "下行 C/N0 输入；关口站≈30、用户终端≈12~18"),
    # --- 激光通信 ---
    P("P_opt", "通信激光发射功率", "W", 1.0, "激光通信", "num", "EIRP_opt=P_opt+G_tx−L_tx"),
    P("D_opt", "光学天线口径 D_opt", "mm", 135, "激光通信", "num", "G_opt=10lg(η(πD/λ)²)，典型 Φ135mm"),
    P("λ_opt", "激光工作波长", "nm", 1550, "激光通信", "num", "1550nm 为主流"),
    P("η_opt", "光学口面效率", "%", 60, "激光通信", "num", "卡塞格林典型 0.6"),
    P("θ_div", "发射发散角 θ_div", "μrad", 100, "激光通信", "num", "指向损耗 L=12(σ_jit/θ_div)²"),
    P("d_isl", "星间距离 d_isl", "km", 5000, "激光通信", "num", "LEO 星座典型 5000km"),
    P("G_edfa", "EDFA 增益", "dB", 25, "激光通信", "num", "噪声指数约 5dB"),
    P("S_opt", "接收灵敏度（@1Gbps）", "dBm", -42, "激光通信", "num",
      "P_req=S_opt+10lg(R/1Gbps)；DPSK 优于 OOK 约 6dB"),
    P("CN_dpsk", "DPSK 解调门限", "dB", 8.0, "激光通信", "num", "c-19 约 8dB"),
    P("EIRP_opt", "激光发射 EIRP", "dBW", 105, "激光通信", "num", "典型 105dBW，可由 P_opt/G_opt 自动算"),
    P("GT_opt", "激光接收 G/T（等效）", "dB/K", 118, "激光通信", "num", "知识图谱等效参数，光学链路实际用灵敏度模型"),
    P("σ_track", "精跟踪精度 σ_track", "μrad", 0.8, "激光通信", "num", "c-18 须 ≤ 1μrad"),
    P("σ_jit", "指向抖动 σ_jit", "μrad", 3.0, "激光通信", "num", "c-18/c-19 瞬时耦合损耗"),
    P("P_acq", "捕获概率 P_acq", "%", 97, "激光通信", "num", "c-18 须 ≥ 95%"),
    P("t_acq", "捕获时间 t_acq", "s", 30, "激光通信", "num", "c-18 影响星座组网可用度"),
    P("θ_fsm", "FSM 偏转范围", "mrad", 3.0, "激光通信", "num", "须覆盖平台微振动"),
    P("L_turb", "大气湍流代价", "dB", 1.5, "激光通信", "num", "c-19 星地链路闪烁/相位噪声"),
    P("P_cloud", "云遮蔽概率", "%", 8, "激光通信", "num", "c-19 星地链路须站址分集规避"),
    P("R_isl", "星间激光链路速率", "Gbps", 10, "激光通信", "num", "c-19 典型 5/10Gbps"),
    P("R_sgl", "星地激光链路速率", "Gbps", 5, "激光通信", "num", "c-19"),
    P("m_laser", "激光分系统质量", "kg", 45, "激光通信", "num", "c-17"),
    P("P_laser", "激光分系统功耗", "W", 180, "激光通信", "num", "c-17"),
    # --- 星内数据链路 ---
    P("R_pdl", "载荷数据产生率 R_pdl", "Mbps", 1200, "星内数据", "num", "c-20 须 ≤ R_bus×CR"),
    P("T_blind", "最长不可见时段", "min", 15, "星内数据", "num", "c-20 E_store ≥ R_pdl×T_blind/CR"),
    P("CR", "数据压缩比 CR", "", 4, "星内数据", "num", "c-20 CCSDS 压缩，等效降低总线与存储需求"),
    P("R_bus", "数据总线速率 R_bus", "Mbps", 4000, "星内数据", "num", "c-20 须 ≥ R_pdl/CR"),
    P("E_store", "存储容量 E_store", "Tbit", 4.0, "星内数据", "num", "c-20"),
    P("R_bb", "基带处理速率 R_bb", "Mbps", 2000, "星内数据", "num", "c-20"),
    P("R_dpu", "DPU 处理速率", "Mbps", 1500, "星内数据", "num", "须 ≥ R_pdl"),
    P("AI_TOPS", "AI 推理算力", "TOPS", 20, "星内数据", "num", "目标/云检测与业务预测"),
    P("MIPS", "星载计算机能力", "MIPS", 4000, "星内数据", "num", "FDIR 覆盖度"),
    P("N_hop", "组网最大跳数", "", 2, "星内数据", "num", "星上组网链路时延"),
    P("t_rec", "重构生效时间 t_rec", "s", 5, "星内数据", "num", "在轨重构配置链路"),
    P("BER_int", "星内链路误码率", "", 1e-12, "星内数据", "num", "载荷数据链路 BER"),
    P("m_ipu", "智能处理分系统质量", "kg", 60, "星内数据", "num", "c-17"),
    P("P_ipu", "智能处理分系统功耗", "W", 220, "星内数据", "num", "c-17"),
    # --- 指标预算与货架 ---
    P("EIRP_req", "EIRP 需求", "dBW", 65, "指标预算", "num", "c-22 EIRP_ant ≥ EIRP_req"),
    P("GT_req", "G/T 需求", "dB/K", 25, "指标预算", "num", "c-22 GT_ant ≥ GT_req"),
    P("C_req", "系统容量需求 C_req", "Gbps", 20, "指标预算", "num", "c-12 C_sys ≥ C_req"),
    P("M_budget", "载荷质量预算", "kg", 480, "指标预算", "num", "c-17 M_pay ≤ M_budget（裕度≥10%）"),
    P("P_budget", "载荷功耗预算", "W", 1900, "指标预算", "num", "c-17 P_pay ≤ P_budget（裕度≥10%）"),
    P("N_gap", "货架缺口数 N_gap", "", 2, "指标预算", "num", "c-21 目标 → 0"),
    P("H_scheme", "整体货架水平 H", "", 3, "指标预算", "select", "c-21 目标 → 4（飞行继承货架）",
      ["1", "2", "3", "4"]),
    P("M_target", "目标链路余量", "dB", 3.0, "指标预算", "num", "c-10 硬判据 M ≥ 3dB"),
]

PARAM_GROUPS = ["任务轨道", "频段规划", "天线", "发射通道", "接收通道", "转发器",
                "地面站", "激光通信", "星内数据", "指标预算"]

# ----------------------------------------------------------------
# 场景预设
# ----------------------------------------------------------------
PRESETS = {
    "geo_ka_hts": dict(
        label="GEO Ka 高通量（多波束 · DTP）",
        desc="GEO 轨道、Ka 频段、64 波束反射面多波束天线、DTP 柔性转发，面向宽带接入与关口站馈电。",
        values=dict(orbit="GEO", d_slant=38000, d_dl=38000, el_deg=30, A_avail="99.9", L_life=15,
                    band="Ka", f_up=30.0, f_down=20.0, A_up_ref=12.0, A_dn_ref=7.0,
                    A_atm=0.4, A_atm_dl=0.2, B_total=2500, k_reuse="4",
                    ant_type="反射面天线", D_ap=2.5, η_ill=68, θ_scan=0, N_beam=64, B_beam=125,
                    B_carrier=36, Mode="多波束", Mode_req="多波束", N_bf=64, N_port=64, N_sch=64,
                    δ_surf=0.20, δ_dep=0.20, θ_e=0.05, L_feed=0.8, T_ant=50,
                    amp_type="TWTA", P_out=180, η_pa=58, L_tx=4.7, arch="DTP数字透明处理器",
                    B_trp=1000, C_sw=150, N_ch=32, B_sub=40,
                    NF_lna=1.6, G_lna=35, EIRP_gs=75, GT_gs=15,
                    EIRP_req=65, GT_req=25, C_req=20, M_budget=480, P_budget=1900,
                    m_ant=120, P_ant=350, m_trp=180, P_trp=900, m_laser=45, P_laser=180,
                    m_ipu=60, P_ipu=220, R_bb=2000, R_dpu=1500, N_gap=2, H_scheme="3",
                    d_isl=5000, R_isl=10, R_pdl=1200, T_blind=15, CR=4, R_bus=4000, E_store=4.0)),
    "geo_ku_single": dict(
        label="GEO Ku 单波束（透明转发）",
        desc="GEO 轨道、Ku 频段、2.5m 反射面单波束、透明转发器，面向广播与窄带专网。",
        values=dict(orbit="GEO", d_slant=38000, d_dl=38000, el_deg=25, A_avail="99.9", L_life=15,
                    band="Ku", f_up=14.0, f_down=12.0, A_up_ref=2.5, A_dn_ref=2.0,
                    A_atm=0.15, A_atm_dl=0.12, B_total=500, k_reuse="1",
                    ant_type="反射面天线", D_ap=2.5, η_ill=65, θ_scan=0, N_beam=1, B_beam=36,
                    B_carrier=36, Mode="单波束", Mode_req="单波束", N_bf=1, N_port=1, N_sch=1,
                    δ_surf=0.35, δ_dep=0.30, θ_e=0.08, L_feed=0.8, T_ant=40,
                    amp_type="TWTA", P_out=140, η_pa=60, L_tx=4.2, arch="透明转发器",
                    B_trp=36, C_sw=10, N_ch=1, B_sub=36,
                    NF_lna=1.2, G_lna=40, EIRP_gs=72, GT_gs=22,
                    EIRP_req=48, GT_req=8, C_req=0.05, M_budget=280, P_budget=1100,
                    m_ant=85, P_ant=90, m_trp=110, P_trp=520, m_laser=0, P_laser=0,
                    m_ipu=25, P_ipu=80, R_bb=300, R_dpu=200, N_gap=0, H_scheme="4",
                    d_isl=5000, R_isl=0, R_sgl=0, R_pdl=150, T_blind=20, CR=2,
                    R_bus=1000, E_store=1.0)),
    "leo_broadband": dict(
        label="LEO 宽带星座（相控阵 · 再生 · 激光 ISL）",
        desc="LEO 550km、Ka 用户链路、1024 阵元相控阵、再生转发 + 激光星间组网，面向低时延宽带。",
        values=dict(orbit="LEO", d_slant=1200, d_dl=1200, el_deg=40, A_avail="99.5", L_life=7,
                    band="Ka", f_up=30.0, f_down=20.0, A_up_ref=6.0, A_dn_ref=3.5,
                    A_atm=0.4, A_atm_dl=0.2, B_total=1500, k_reuse="4",
                    ant_type="相控阵天线", D_ap=0.8, N_el=1024, G_el=6.0, η_ill=70, θ_scan=45,
                    N_beam=16, B_beam=250, B_carrier=62, Mode="在轨重构", Mode_req="波束跳变",
                    N_bf=16, N_port=16, N_sch=16,
                    δ_surf=0.20, δ_dep=0.15, θ_e=0.10, L_feed=0.5, T_ant=60,
                    amp_type="MPA", P_out=60, η_pa=42, L_tx=3.5, arch="再生转发器",
                    B_trp=1000, C_sw=60, N_ch=16, B_sub=64, ΔM_reg=4.5, τ_reg=30,
                    NF_lna=1.6, G_lna=35, EIRP_gs=68, GT_gs=12,
                    EIRP_req=45, GT_req=8, C_req=10, M_budget=320, P_budget=1900,
                    m_ant=95, P_ant=680, m_trp=70, P_trp=480, m_laser=38, P_laser=160,
                    m_ipu=42, P_ipu=190, P_tr=0.5, R_bb=3000, R_dpu=2600, N_gap=3, H_scheme="2",
                    d_isl=4500, R_isl=10, R_sgl=5, P_opt=1.0, D_opt=135, λ_opt=1550,
                    σ_track=0.8, σ_jit=3.0, P_acq=97, t_acq=25, S_opt=-42,
                    R_pdl=2500, T_blind=8, CR=4, R_bus=8000, E_store=3.0)),
    "leo_d2d": dict(
        label="LEO L 波段手机直连 D2D（大口径相控阵）",
        desc="LEO 500km、S 频段、超大口径可展开相控阵，面向普通手机直连（手持终端 G/T 极低）。",
        values=dict(orbit="LEO", d_slant=900, d_dl=900, el_deg=25, A_avail="99.0", L_life=7,
                    band="S", f_up=2.1, f_down=2.3, A_up_ref=0.3, A_dn_ref=0.3,
                    A_atm=0.05, A_atm_dl=0.05, B_total=240, k_reuse="4",
                    ant_type="相控阵天线", D_ap=12.0, N_el=2500, G_el=4.0, η_ill=60, θ_scan=35,
                    N_beam=48, B_beam=5, B_carrier=5, Mode="波束跳变", Mode_req="波束跳变",
                    N_bf=48, N_port=48, N_sch=48,
                    δ_surf=2.0, δ_dep=1.5, θ_e=0.15, L_feed=0.4, T_ant=80,
                    amp_type="SSPA", P_out=80, η_pa=45, L_tx=2.8, arch="再生转发器",
                    B_trp=60, C_sw=20, N_ch=60, B_sub=1, ΔM_reg=5.0, τ_reg=25,
                    NF_lna=0.8, G_lna=40, EIRP_gs=55, GT_gs=-12,
                    EIRP_req=32, GT_req=-5, C_req=0.5, M_budget=520, P_budget=3200,
                    m_ant=210, P_ant=1650, m_trp=95, P_trp=620, m_laser=35, P_laser=150,
                    m_ipu=55, P_ipu=240, P_tr=0.6, R_bb=800, R_dpu=700, N_gap=5, H_scheme="2",
                    d_isl=3000, R_isl=5, R_sgl=0, R_pdl=600, T_blind=12, CR=3,
                    R_bus=3000, E_store=2.0)),
}

# ----------------------------------------------------------------
# 链路定义：id → (名称, 分类, 方向, kind)
#   kind: rf_rx(接收射频链) / rf_tx(发射射频链) / laser(光学链) / data(数据链) / arch(体制链)
#   chain 从知识图谱 ontologies[].chain 读取，此处仅登记元信息
# ----------------------------------------------------------------
LINK_META = {
    "ant_tx_path":     dict(dir="tx",   kind="rf_tx",  cat="天线分系统"),
    "ant_rx_path":     dict(dir="rx",   kind="rf_rx",  cat="天线分系统"),
    "beam_link":       dict(dir="ctl",  kind="rf_tx",  cat="天线分系统"),
    "transparent":     dict(dir="both", kind="arch",   cat="转发器分系统"),
    "regenerative":    dict(dir="both", kind="arch",   cat="转发器分系统"),
    "dtp":             dict(dir="both", kind="arch",   cat="转发器分系统"),
    "uplink":          dict(dir="rx",   kind="rf_rx",  cat="转发器分系统"),
    "downlink":        dict(dir="tx",   kind="rf_tx",  cat="转发器分系统"),
    "interbeam_link":  dict(dir="both", kind="data",   cat="转发器分系统"),
    "regen_channel":   dict(dir="both", kind="data",   cat="转发器分系统"),
    "isl_laser":       dict(dir="both", kind="laser",  cat="激光通信分系统"),
    "sgl_laser":       dict(dir="both", kind="laser",  cat="激光通信分系统"),
    "payload_data_link": dict(dir="both", kind="data", cat="智能处理分系统"),
    "onboard_net":     dict(dir="both", kind="data",   cat="智能处理分系统"),
    "reconfig_link":   dict(dir="both", kind="data",   cat="智能处理分系统"),
}
